In [3]:
import numpy as np
arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [1]:
list=[]
n = int(input())
for i in range(0,5):
    ele = int(input())
    list.append(ele)
print(list)    

5
5
8
9
6
2
[5, 8, 9, 6, 2]


In [1]:
import numpy as np
 
# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
 

 # Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)
 

 
 # Printing size (total number of elements) of array
print("Size of array: ", arr.size)
 

No. of dimensions:  2
Size of array:  6


In [8]:
import numpy as np 
  
a = np.array([[1, 2], 
              [3, 4]]) 
  
b = np.array([[5, 6], 
              [7, 8]]) 
  
# vertical stacking 
print("Vertical stacking:\n", np.vstack((a, b))) 
  
# horizontal stacking 
print("\nHorizontal stacking:\n", np.hstack((a, b))) 
  


Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]


In [12]:
from collections import Counter
numbers = [1, 2, 2, 3, 3, 4, 5]


def get_unique_numbers(numbers):

    list_of_unique_numbers = []

    unique_numbers = set(numbers)

    for number in unique_numbers:
        list_of_unique_numbers.append(number)

    return list_of_unique_numbers


print(get_unique_numbers(numbers))

items = Counter(numbers).keys() 
print("Count of unique items in the list are:", len(items)) 

[1, 2, 3, 4, 5]
No of unique items in the list are: 5
